name: CI
on: [push, pull_request]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with: {python-version: '3.10'}
      - name: Install deps
        run: |
          pip install -r examples/python_server/requirements.txt
          pip install pytest black flake8
      - name: Format check
        run: black --check .
      - name: Lint check
        run: flake8
      - name: Unit tests
        run: pytest -q
  sbom-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft packages dir:.
      - name: Container scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with: {image-ref: 'yourdocker/repo:latest'}
